### Site metadata ###

site_name: CRNPy Documentation
site_description: CRNPy is a Python package for the estimation of soil moisture from cosmic-ray neutron data. It provides routines for the correction of neutron counts for environmental effects, the calculation of soil moisture from corrected neutron counts, and the calibration of cosmic-ray neutron probes.
site_url: https://soilwater.github.io/crnpy/
repo_url: https://github.com/soilwater/crnpy

### Build settings ###

theme:
  name: 'material'
  logo: img/logo/crnpy-logo-mini.svg
  favicon: img/logo/favicon.png

plugins:
- search
- autorefs
- mkdocs-jupyter:
    remove_tag_config:
      remove_input_tags:
        - hide-input
- mkdocstrings

nav:
  - Home: index.md
  - Correction routines: correction_routines.md
  - Examples:
      - examples/overview.md
      - 'Example 1': examples/stationary/example_RDT_station.ipynb
      - 'Example 2': examples/rover/Hydroinnova_rover_example.ipynb
      - 'Device calibration': examples/calibration/calibration.ipynb
  - Reference: reference.md


extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

markdown_extensions:
  - admonition